apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: ["sh", "-c", "echo 'Hello, Kubernetes CronJob!' > /mnt/data/cronjob.txt"]
        volumeMounts:
        - mountPath: /mnt/data
          name: example-storage
      restartPolicy: OnFailure
      volumes:
      - name: example-storage
        persistentVolumeClaim:
          claimName: example-pvc